# xfce related packages
- name: Set release to testing
  set_fact:
    default_release: "{{ apt_current_testing }}"
  when: install_xfce_from_testing

- name: Set release to stable
  set_fact:
    default_release: "{{ apt_current_stable }}"
  when: not install_xfce_from_testing

- name: installing xfce4 related packages
  apt:
    name: "{{ item }}"
    state: present
    default_release: "{{ default_release}}"
  with_items:
  - task-xfce-desktop
  - xfce4-goodies
  when: include_xfce4
  tags: apt

- name: tweaking default xfce keybindings
  template: src=xfce4-keyboard-shortcuts.xml.j2 dest=/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
  tags: wm

- name: installing xrdp
  apt: name={{ item }} state=present
  with_items:
  - xrdp
  tags: apt
  when: install_xrdp

- name: update lightdm config file
  template:
    src: lightdm.conf.j2
    dest: /etc/lightdm/lightdm.conf
    mode: 0644
    owner: root
    group: root
  when: include_xfce4
  notify: restart lightdm
