# xfce related packages
- name: installing xfce4 related packages
  apt: name={{ item }} state=latest
  with_items:
  - task-xfce-desktop
  - xrdp
  - xfce4-goodies
  when: include_xfce4
  tags: apt

- name: tweaking default xfce keybindings
  template: src=xfce4-keyboard-shortcuts.xml.j2 dest=/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
  tags: wm
