# installation of grouped items

- name: installing other packages
  apt: name={{ item }} state=latest
  with_items:
  - iceweasel
  - git
  tags: apt
  
- name: installing admin packages
  apt: name={{ item }} state=latest
  with_items:
  - wireshark
  - tcpdump
  - curl
  tags: apt
  when: include_admin_packages
  
- name: installing flash
  apt: name=flashplugin-nonfree state=latest
  tags: apt
  when: include_flash
