# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "deb8-base"
  config.vm.hostname = "workstation-xfce4-test"

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.nested = false
    libvirt.memory = 2048
  end

#  config.vm.synced_folder './', '/vagrant', type: '9p', disabled: false, accessmode: "squash", owner: "vagrant"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

  config.vm.provision :shell,
      inline: "apt-get update"
      
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
#    ansible.inventory_path = "inventory"
#    ansible.groups = {
#      "routers" => ["ipsrouter"],
#      "servers" => ["ipsclient", "ipsserver"]
#    }
  end

end
