# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.define "debian-jessie" do |server|
    server.vm.box = "debian/jessie64"
    server.vm.hostname = "ws-debian-jessie"
  end

  config.vm.define "debian-stretch" do |server|
    server.vm.box = "debian/stretch64"
    server.vm.hostname = "ws-debian-stretch"
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.nested = false
    libvirt.memory = 2048
    libvirt.video_type = 'qxl'
  end

#  config.vm.synced_folder './', '/vagrant', type: '9p', disabled: false, accessmode: "squash", owner: "vagrant"
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false, disabled: true

  $script = <<SCRIPT
apt-get update
apt-get upgrade
SCRIPT
#
#  config.vm.provision "shell", inline: $script

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.compatibility_mode = "2.0"
#    ansible.inventory_path = "inventory"
#    ansible.groups = {
#      "routers" => ["ipsrouter"],
#      "servers" => ["ipsclient", "ipsserver"]
#    }
  end

end
